### ISSUE TITLE
New sub command that behavior like a `bundle exec`.

### ISSUE THREAD

**Issue by osamingo** [ktr0731/dept#1]
I wanna more easy call to bundled commands.
Because We dislike thinking and editing to `$PATH` at multiple environment in team development.

**Comment by ktr0731** [comment]
Thank you for submitting a cool proposal!
I think it looks good. Most users will want to use tools transparently. I'm going to add its command.

**Comment by ktr0731** [comment]
implemented at #2, thank you!

**Comment by osamingo** [comment]
Awesome! 🎉🎉🎉
